/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital;

/**
 *
 * @author Mano
 */
public class Menuframe extends javax.swing.JFrame {

    /**
     * Creates new form Menuframe
     */
    public Menuframe() {
        initComponents();
        this.setSize(1220,500);
    }
 In_PatientIno In_PatientIno= new In_PatientIno() ;
  HospitalPatienInfo HospitalPatienInfo=new HospitalPatienInfo();
  Out_patient Out_patient=new Out_patient();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        out_Patient = new javax.swing.JMenuItem();
        In_Patient = new javax.swing.JMenuItem();
        patient = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Logout = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jMenu1.setText("All Information");

        out_Patient.setText("Out_pation info");
        out_Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                out_PatientActionPerformed(evt);
            }
        });
        jMenu1.add(out_Patient);

        In_Patient.setText("In_patient info");
        In_Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                In_PatientActionPerformed(evt);
            }
        });
        jMenu1.add(In_Patient);

        patient.setText("patient_Info");
        patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientActionPerformed(evt);
            }
        });
        jMenu1.add(patient);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Logout");

        Logout.setText("log out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenu2.add(Logout);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Insert and Update");

        jMenuItem8.setText("hospital_patient");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void out_PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_out_PatientActionPerformed


        
        
           this.jPanel1.setVisible(false);
        HospitalPatienInfo.jPanel1.setVisible(false);
        Out_patient.jPanel1.setVisible(true);
        
        In_PatientIno.jPanel1.setVisible(false);
  
         In_PatientIno.setVisible(false);
        
         HospitalPatienInfo.setVisible(false);
         Out_patient.setVisible(false);
         Out_patient.jPanel1.setSize(1220,500);
         Out_patient.jTable1.setSize(1200,500);
         this.setSize(1220,500);
        this.add(Out_patient.jPanel1);
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_out_PatientActionPerformed

    private void In_PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_In_PatientActionPerformed
        
        this.jPanel1.setVisible(false);
        HospitalPatienInfo.jPanel1.setVisible(false);
        In_PatientIno.jPanel1.setVisible(true);
        
          Out_patient.jPanel1.setVisible(false);
  
         Out_patient.setVisible(false);
        
         HospitalPatienInfo.setVisible(false);
         In_PatientIno.setVisible(false);
         In_PatientIno.jPanel1.setSize(1220,500);
         In_PatientIno.jTable1.setSize(1200,500);
         this.setSize(1220,500);
        this.add(In_PatientIno.jPanel1);
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_In_PatientActionPerformed

    private void patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientActionPerformed
                 this.jPanel1.setVisible(false);
        HospitalPatienInfo.jPanel1.setVisible(true);
        In_PatientIno.jPanel1.setVisible(false);
        
          Out_patient.jPanel1.setVisible(false);
  
         Out_patient.setVisible(false);
        
         HospitalPatienInfo.setVisible(false);
         In_PatientIno.setVisible(false);
         HospitalPatienInfo.jPanel1.setSize(1220,500);
          HospitalPatienInfo.jTable1.setSize(1200,500);
         this.setSize(1220,500);
         
        this.add(HospitalPatienInfo.jPanel1);
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_patientActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
    this.setVisible(false);
    new welecome().setVisible(true);
        
        
        
    }//GEN-LAST:event_LogoutActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed

                new Insert_patiant().setVisible(true);
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Menuframe().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem In_Patient;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem out_Patient;
    private javax.swing.JMenuItem patient;
    // End of variables declaration//GEN-END:variables
}
