/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mano
 */
public class Out_patient extends javax.swing.JFrame {

    /**
     * Creates new form Out_patient
     */
    public Out_patient() {
        initComponents();
         try {
        
        
        Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "");
        Statement statement=connection.createStatement();
        ResultSet set=statement.executeQuery("SELECT * FROM (SELECT  `patientname` ,`age`,`name`,`address`,`phoneres`,`phonemob`,`patienttypeValue`FROM `patientinfo` INNER JOIN sex INNER JOIN `patienttype`  where `patientinfo`.`gender`=`sex`.`id`)as d WHERE `patienttypeValue`='Out-Patient' ");
        /*
         
         
         
         
         */
        ResultSetMetaData meta=set.getMetaData();
        int c=meta.getColumnCount();
        DefaultTableModel model=new  DefaultTableModel();
        
        for(int i=1;i<=c;i++){
        model.addColumn(meta.getColumnLabel(i));}
        this.jTable1.setModel(model);
        while(set.next())
        {
        Object []raw=new Object[c];
                 for(int j=1;j<=c;j++){
                 raw[j-1]=set.getObject(j);
                 }
                 
                 model.addRow(raw);
        }
        
        
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(rootPane,ex.getMessage() );
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Admin = new javax.swing.JButton();
        patientname = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Admin.setBackground(new java.awt.Color(51, 51, 51));
        Admin.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Admin.setForeground(new java.awt.Color(51, 0, 0));
        Admin.setText("search by name");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientname, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 128, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Admin, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(patientname))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
       
               if(patientname.getText().equals("")){
        
        try {
        
        
        Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "");
        Statement statement=connection.createStatement();
        ResultSet set=statement.executeQuery("SELECT * FROM (SELECT  `patientname` ,`age`,`name`,`address`,`phoneres`,`phonemob`,`patienttypeValue`FROM `patientinfo` INNER JOIN sex INNER JOIN `patienttype`  where `patientinfo`.`gender`=`sex`.`id`)as d WHERE `patienttypeValue`='Out-Patient'");
        /*
         
         
         
         
         */
        ResultSetMetaData meta=set.getMetaData();
        int c=meta.getColumnCount();
        DefaultTableModel model=new  DefaultTableModel();
        
        for(int i=1;i<=c;i++){
        model.addColumn(meta.getColumnLabel(i));}
        this.jTable1.setModel(model);
        while(set.next())
        {
        Object []raw=new Object[c];
                 for(int j=1;j<=c;j++){
                 raw[j-1]=set.getObject(j);
                 }
                 
                 model.addRow(raw);
        }
        
        
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(rootPane,ex.getMessage() );
    }
        
        
        }else{
        
        try {
        
        
        Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "");
        Statement statement=connection.createStatement();
        ResultSet set=statement.executeQuery("SELECT * FROM (SELECT * FROM (SELECT  `patientname` ,`age`,`name`,`address`,`phoneres`,`phonemob`,`patienttypeValue`FROM `patientinfo` INNER JOIN sex INNER JOIN `patienttype`  where `patientinfo`.`gender`=`sex`.`id`)as d WHERE `patienttypeValue`='Out-Patient')as sh WHERE `patientname`='"+patientname.getText()+"'");
        /*
         
         
         
         
         */
        ResultSetMetaData meta=set.getMetaData();
        int c=meta.getColumnCount();
        DefaultTableModel model=new  DefaultTableModel();
        
        for(int i=1;i<=c;i++){
        model.addColumn(meta.getColumnLabel(i));}
        this.jTable1.setModel(model);
        while(set.next())
        {
        Object []raw=new Object[c];
                 for(int j=1;j<=c;j++){
                 raw[j-1]=set.getObject(j);
                 }
                 
                 model.addRow(raw);
        }
        
        
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(rootPane,ex.getMessage() );
    } }
    }//GEN-LAST:event_AdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Out_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Out_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Out_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Out_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Out_patient().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField patientname;
    // End of variables declaration//GEN-END:variables
}
